### ISSUE TITLE
Which image backbone do you use in the experiment?

### ISSUE THREAD

**Issue by synsin0** [westlake-autolab/FusionAD#3]
I read the article but do not find infos about your usage of image backbone. May you reveal which backbone is conducted for this experiment?

**Comment by JieMaMagic** [comment]
Thank you. Your email is received and will be handled  as soon as possible

您的邮件已收到，我会尽快处理

**Comment by ChunyongHu** [comment]
> I read the article but do not find infos about your usage of image backbone. May you reveal which backbone is conducted for this experiment?

Thank you. We used ResNet-101 as the backbone for the image branch, and VoxelNet-0075 as the backbone for the point cloud branch.
