### ISSUE TITLE
Any update on releasing the code for this paper?

### ISSUE THREAD

**Issue by BenLJM** [westlake-autolab/FusionAD#4]
Thanks for sharing your work! It is been 6 months since the repo was initiated, wonder if the implementation of the paper is ready to release.

**Comment by JieMaMagic** [comment]
Thank you. Your email is received and will be handled  as soon as possible

您的邮件已收到，我会尽快处理

**Comment by billbliss3** [comment]
Thanks for sharing your work! It is been 9 months since the repo was initiated, wonder if the implementation of the paper is ready to release.

**Comment by JieMaMagic** [comment]
Thank you. Your email is received and will be handled  as soon as possible

您的邮件已收到，我会尽快处理
